# Generated by Django 5.2.4 on 2025-08-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('run_at', models.DateTimeField()),
                ('is_executed', models.BooleanField(default=False)),
            ],
        ),
    ]
